include:
    - docker-compose-keycloak.yml

services:
    node:
        container_name: node-app
        build:
            context: node
            dockerfile: dockerfile
        user: 1000:1000
        stdin_open: true
        tty: true
        ports:
            - "9460:9460"
        volumes:
            - ./node/source:/home/node/app
        command: sh -c "cd /home/node/app && npm install && npm run start"
        env_file:
            - .env

    ui:
        container_name: ui-app
        build:
            context: ui
            dockerfile: dockerfile
        user: 1000:1000
        stdin_open: true
        tty: true
        ports:
            - "4000:3000"
        environment:
            - KEYCLOAK_AUTH_SERVER_URL=http://keycloak:8080
        volumes:
            - ./ui/source:/home/node/app/ui
            - ${HOME}/.vscode-server-keycloakui:/home/node/.vscode-server
        command: sh -c "cd /home/node/app/ui && npm install && npm run dev"
        env_file:
            - .env

volumes:
    postgres-kc-data:
        driver: local
