services:
    postgres:
        container_name: kc-database
        image: postgres:16-alpine
        volumes:
            - postgres-kc-data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: keycloak
            POSTGRES_PASSWORD: password
            POSTGRES_DB: keycloak
        ports:
            - "5432:5432"

    keycloak:
        container_name: keycloak
        image: quay.io/keycloak/keycloak:22.0
        environment:
            KEYCLOAK_ADMIN: admin
            KEYCLOAK_ADMIN_PASSWORD: password
            KEYCLOAK_LOGLEVEL: INFO
            ROOT_LOGLEVEL: INFO
            KC_DB: postgres
            KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
            KC_DB_USERNAME: keycloak
            KC_DB_PASSWORD: password
        ports:
            - "8080:8080"
        depends_on:
            - postgres
        command: start-dev
